version: "3.9"

services:
  server:
    build:
      context: .
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: chess.eth
    restart: "unless-stopped"
    ports:
      - "3333:3333"
      - "9229:9229"
    volumes:
      - ./:/app
      - /app/node_modules
    links:
      - postgres
    depends_on:
      - postgres
  postgres:
    image: postgres
    volumes:
      - ./scripts/postgres/init_sql.sh:/docker-entrypoint-initdb.d/init_sql.sh
    container_name: bots_postgres
    environment:
      PUID: 1000
      PGID: 1000
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DATABASE: $DATABASE_NAME
    ports:
      - "$DATABASE_PORT:5432"
